### ISSUE TITLE
Issue run matatika lab in windows

### ISSUE THREAD

**Issue by kevinkumar2020** [meltano/edk#207]
Try, to run matatika with `meltano run matatika lab` in windows it's throw error.
meltano version 3.3

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

TypeError: environment can only contain strings
```

**Comment by ReubenFrankel** [comment]
Some more context:

https://docs.python.org/3/library/asyncio-platforms.html#windows

> All event loops on Windows do not support the following methods:
> * `loop.create_unix_connection()` and `loop.create_unix_server()` are not supported. The `[socket.AF](http://socket.AF)_UNIX` socket family is specific to Unix.
> * `loop.add_signal_handler()` and `loop.remove_signal_handler()` are not supported

https://github.com/meltano/edk/blob/df18cb8431303f7c401c5c3611fba65f8fcead78/meltano/edk/process.py#L138-L141
